// Auto-generated market address mapping
// DO NOT EDIT MANUALLY - generated by run-anvil-deploy.sh

export const MARKET_ADDRESS_MAP: Record<string, string> = {
  '0x748f3d7c82a16514e7c0a770c43aec0a281f1b75': 'ETH-USD',
  '0xfab862bed5efc48fa9e46ea41902d5597a4ec71f': 'SOL-USD',
  '0xe42cc83be6660a3b40aba4548d2c742a5053851b': 'BTC-USD',
};

export function getMarketIdFromAddress(address: string): string {
  return MARKET_ADDRESS_MAP[address.toLowerCase()] || 'ETH-USD';
}
