// Auto-generated market address mapping
// DO NOT EDIT MANUALLY - generated by run-anvil-deploy.sh

export const MARKET_ADDRESS_MAP: Record<string, string> = {
  '0x60f02157159b12bae61f2adce391b88324e4606e': 'ETH-USD',
  '0xc0cbd77ba95788e2462b755ee1fd42c6a4946901': 'SOL-USD',
  '0xaf7adbc53376d6ecf6668758eeddef4aa162eab2': 'BTC-USD',
};

export function getMarketIdFromAddress(address: string): string {
  return MARKET_ADDRESS_MAP[address.toLowerCase()] || 'ETH-USD';
}
