// Auto-generated market address mapping
// DO NOT EDIT MANUALLY - generated by run-anvil-deploy.sh

export const MARKET_ADDRESS_MAP: Record<string, string> = {
  '0x33c5e0c6db699365b5d386069b2b2505c22db05f': 'ETH-USD',
  '0x213e6e8c056948280c1e9b061d4e8479bbd7be23': 'SOL-USD',
  '0x8bd2b8aa96e00cd7c888a1ee2cdc68551fb3b467': 'BTC-USD',
};

export function getMarketIdFromAddress(address: string): string {
  return MARKET_ADDRESS_MAP[address.toLowerCase()] || 'ETH-USD';
}
